// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: chirps.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps(id,body,author_id,created_at,upadated_at) VALUES($1,$2,$3,$4,$5)
RETURNING id, body, author_id, created_at, upadated_at
`

type CreateChirpParams struct {
	ID         int32
	Body       sql.NullString
	AuthorID   uuid.UUID
	CreatedAt  time.Time
	UpadatedAt sql.NullTime
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp,
		arg.ID,
		arg.Body,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpadatedAt,
	)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpadatedAt,
	)
	return i, err
}
