// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Chirp struct {
	ID        int32
	Body      string
	AuthorID  uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	Name      string
	Email     string
	Passwd    []byte
	ID        uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
